### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by TonyKim02**
The following branch has successfully integrated MongoDB with gradle support for github-classroom unit tests.

### CODE REVIEW

**Comment by ShaanPurewal** [comment]
Please change the java version properties (within the build.gradle file) so github classrooms will run without error.

**Comment by TonyKim02** [comment]
Fixed java version + removed unused test files

**Comment by ShaanPurewal** [comment]
lgstm!

**Comment by ShaanPurewal** [comment]
Please remove the public key to our database prior to merging this PR

**Comment by zixm** [comment]
Please remove the GET request test case that stores into the DB within RootController.java

**Comment by ShaanPurewal** [comment]
Please stay consistant with style, Account_Repo should follow the camelCase style we agreed during out initial meeting.

**Comment by TonyKim02** [comment]
fixed changes above

**Comment by zixm** [comment]
lgtm!

**Comment by TonyKim02** [comment]
Overall this PR included the following implementations:

- Controller directory
- Repository directory
- use-cases directory
- Running QuestApplication.java file for multiple use (unit test, usecases, etc).
- mongorepo implementation that allows editing the DB (CRUD operations)

Styling & Organization
- basic camelCasing (Name Convention)
- Mongo Repository compatible annotations (for clean data storage and retrieval)

Code Smells
- removed most if not all dead code

Clean & SOLID
- Adheres to Clean & SOLID principle to the best of my abilities. (Applied single responsibility, dependency inversion)

Testing
- include base testing for contributors to built off of

Functionality
- I intend to make contributors to be able to make custom repos and collections within mongorepo that allows data manipulation as they want.

**Pull request merged**
